timeout: 5m

notifications:
  enabled: true
  at:
  - 5m
  - 1m
  - 30s
  - 10s

dbus:
  service: org.bluez
  adapter_iface: org.bluez.Adapter1
  adapter_path: /org/bluez/hci0
  device_iface: org.bluez.Device1
